DATASET:
  TRAIN: "/data/datasets/coco-darknet/train2017.txt"
  VAL: "/data/datasets/coco-darknet/val2017.txt"
  NAMES: "configs/coco.names"
MODEL:
  NUM_CLASSES: 80
  INPUT_WIDTH: 352
  INPUT_HEIGHT: 352
TRAIN:
  LEARNING_RATE: 0.001
  WARMUP_EPOCH: 5
  BATCH_SIZE: 256
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250
